version: '3'

services:
    front:
        image: oven/bun:1.0.28
        build: 
            dockerfile: Dockerfile
            context: .
        restart: unless-stopped
        ports:
            - 3000:3000